source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@git.1kxun.com:9922/ios/CocoaPods-Specs.git'

use_frameworks!
platform :ios, '8.0'

target 'TCNRequest_Example' do
  pod 'TCNRequest', :path => '../'

  target 'TCNRequest_Tests' do
    inherit! :search_paths

    
  end
end
